import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GameboardProvider from "@/hooks/context";
import ConvexClientProvider from "@/providers/convexclient";
import Timer from "@/components/timer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ConvexClientProvider>
                    <GameboardProvider>
                        <Timer gameStarted={true} />
                        {children}
                    </GameboardProvider>
                </ConvexClientProvider>
            </body>
        </html>
    );
}
