import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import GameboardProvider from "@/hooks/context";
import ConvexClientProvider from "@/providers/convexclient";
import Script from "next/script";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js" />
                <Script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/Flip.min.js" />
                <ConvexClientProvider>
                    <GameboardProvider>{children}</GameboardProvider>
                </ConvexClientProvider>
            </body>
        </html>
    );
}
